### ISSUE TITLE
Possible cache issue

### ISSUE THREAD

**Issue by gbalabasquer** [makerdao/pg-graphql#1]
I had created a new CDP via a support contract. That support contract creates the CDP and immediately transfer it to your account in the same tx.

`{ getCup(id: 2891) { lad ink art actions { nodes { act ink art tab per pip arg guy tx time } } } }`

The result is: 

```
{
  "data": {
    "getCup": {
      "lad": "0xAdDcC71eAA462b0B94a01980A395450c9ab74466",
      "ink": "0.09998436012365433",
      "art": "1",
      "actions": {
        "nodes": [
          {
            "act": "GIVE",
            ...
          },
          {
            "act": "DRAW",
            ...
          },
          {
            "act": "LOCK",
            ...
          },
          {
            "act": "OPEN",
            ...
          }
        ]
      }
    }
  }
}
```

`0xAdDcC71eAA462b0B94a01980A395450c9ab74466` is my account, which is correct. This query also also detects the event which gave the CDP to it.

However if I run:

`{ allCups( condition: { lad: "0xAdDcC71eAA462b0B94a01980A395450c9ab74466" } ) { nodes { id, block} } }` the result is empty.

So, it seems to be some cache issue in one of the queries and not a sync problem at all.

The CDP seems stuck under the support contract:

`{ allCups( condition: { lad: "0xADB7c74bCe932fC6C27ddA3Ac2344707d2fBb0E6" } ) { nodes { id, block} } }`

```
{
  "data": {
    "allCups": {
      "nodes": [
        {
          "id": 2891,
          "block": 9005378
        },
        {
          "id": 2759,
          "block": 8883479
        }
      ]
    }
  }
}
```

There is also another CDP there (2759), which that case is even more strange, as if you call to `{ getCup(id: 2759) { lad ink art actions { nodes { act ink art tab per pip arg guy tx time } } } }` the CDP seems to be attached as well to the support contract but also registered the `give` method. So for this case, it also has wrong the `lad` value in the `getCup` method

**Comment by desaperados** [comment]
@gbalabasquer I wasn't able to reproduce with this exact query but I did discover an issue which I think is responsible for the behaviour that you describe.

The transaction index was not being taken into account when retrieving cup state which meant that cup state was not being correctly represented in the case of multiple actions in the same transaction.

I've updated cup state retrieval to take transaction index into account which appears to have addressed the issue as you can see in this example:

<img width="1085" alt="screen shot 2018-10-18 at 11 08 11 am" src="https://user-images.githubusercontent.com/5028/47119114-23284780-d2c6-11e8-9366-308a89c1b31b.png">
